serving:
  http_port: 65322
  log_timings: True
  create_logging_endpoints: True
  extra_start_args:
    -Xmx8g
  output_data_format: NUMPY
steps:
  - type: "IMAGE"
    dimensions_configs: {}
    image_processing_initial_layout: "NCHW"
    image_processing_required_layout: "NHWC"
    image_transform_processes: {}
    input_column_names: {}
    input_names:
      - "default"
    input_schemas: {}
    original_image_height: 0
    original_image_width: 0
    output_column_names: {}
    output_names:
      - "default"
    output_schemas: {}
    update_ordering_before_transform: false
  - type: KERAS
    path: keras_cnn_model.h5
    input_names:
      - default
    input_column_names:
      default:
        - NDArray
    input_schemas:
      default:
        - NDArray
    output_names:
      - default
    output_column_names:
      default:
        - NDArray
    output_schemas:
      default:
        - NDArray
client:
  port: 65322
  output_names:
    - default
  input_data_format: NUMPY
  output_data_format: NUMPY
