serving:
  http_port: 65322
  log_timings: True
  extra_start_args:
    -Xmx8g
  output_data_format: NUMPY
steps:
  dl4j_inference_step:
    type: DL4J
    model_loading_path: D:\\Users\\chiawei\\Documents\\data\\bert.zip #C:\\Users\\chiaw\\AppData\\Local\\Temp\\dl4j_csv_mln.zip
    input_names:
      - feature
      - mask
    input_column_names:
      default:
        - NDArray
        - NDArray
    input_schemas:
      default:
        - NDArray
        - NDArray
    output_names:
      - default
    output_column_names:
      default:
        - NDArray
    output_schemas:
      default:
        - NDArray
client:
  port: 65320
  output_names:
    - default
  input_data_format: NUMPY
  output_data_format: NUMPY
