serving:
  http_port: 65322
  log_timings: True
  create_logging_endpoints: True
  extra_start_args:
    -Xmx8g
  output_data_format: NUMPY
steps:
  dl4j_inference_step:
    type: DL4J
    model_loading_path: D:\\Users\\chiawei\\Documents\\data\\dl4j_csv_graph.zip #C:\\Users\\chiaw\\AppData\\Local\\Temp\\dl4j_csv_mln.zip
    input_names:
      - default
    output_names:
      - default
client:
  port: 65322
  output_names:
    - default
  input_data_format: NUMPY
  output_data_format: NUMPY
