serving:
  http_port: 65322
  log_timings: True
  create_logging_endpoints: True
  extra_start_args:
    -Xmx8g
  output_data_format: NUMPY
steps:
  dl4j_inference_step0:
    type: DL4J
    model_loading_path: C:\\Users\\chiaw\\Documents\\data\\konduit-serving-use-cases\\3-1-DL4J-HelloWorld\\dl4j_csv_graph.zip
    input_names:
      - default
    output_names:
      - default
  dl4j_inference_step1:
    type: DL4J
    model_loading_path: C:\\Users\\chiaw\\Documents\\data\\konduit-serving-use-cases\\3-1-DL4J-HelloWorld\\dl4j_csv_graph.zip
    input_names:
      - default
    output_names:
      - default
client:
  port: 65322
  output_names:
    - default
  input_data_format: NUMPY
  output_data_format: NUMPY
