serving:
  http_port: 65322
  log_timings: True
  extra_start_args:
    -Xmx8g
  output_data_format: NUMPY
  log_timings: True
  create_logging_endpoints: True
steps:
  tokenizer_preprocessing_step:
    type: WORD_TOKENIZER
    vocab_path: C:\\Users\\chiaw\\Documents\\data\\konduit-serving-use-cases\\3-2-DL4J-LSTM-PythonClient\\bert-base-uncased-vocab.txt
    sentence_max_len: 256
    input_names:
      - default
    input_column_names:
      default:
        - String
    input_schemas:
      default:
        - String
    output_names:
      - default
    output_column_names:
      default:
        - NDArray
    output_schemas:
      default:
        - NDArray
client:
  port: 65322
  output_names:
    - output
  input_data_format: JSON
  output_data_format: NUMPY
