serving:
  http_port: 65322
  log_timings: True
  extra_start_args:
    -Xmx8g
  output_data_format: NUMPY
steps:
  python_step:
    type: PYTHON
    python_code: |
      first += 2
      second = first
    python_inputs:
      first: NDARRAY
    python_outputs:
      second: NDARRAY
client:
  port: 65322
  output_names:
    - default
  input_data_format: NUMPY
  output_data_format: NUMPY
