serving:
  http_port: 65322
  extra_start_args:
    -Xmx8g
  output_data_format: NUMPY
  log_timings: True
  create_logging_endpoints: True
steps:
  tokenizer_preprocessing_step:
    type: WORDPIECE_TOKENIZER
    vocab_path: C:\\Users\\chiaw\\Documents\\data\\konduit-serving-use-cases\\3-3-DL4J-LSTMTextClassification-MultiSteps\\bert-base-uncased-vocab.txt
    sentence_max_len: 256
    input_names:
      - sentence
    input_column_names:
      default:
        - String
    input_schemas:
      default:
        - String
    output_names:
      - default
    output_column_names:
      default:
        - NDArray
    output_schemas:
      default:
        - NDArray
  dl4j_inference_step:
    type: DL4J
    model_loading_path: C:\\Users\\chiaw\\Documents\\data\\konduit-serving-use-cases\\3-3-DL4J-LSTMTextClassification-MultiSteps\\bert.zip #C:\\Users\\chiaw\\AppData\\Local\\Temp\\dl4j_csv_mln.zip
    input_names:
      - default
    input_column_names:
      default:
        - NDArray
    input_schemas:
      default:
        - NDArray
    output_names:
      - default
    output_column_names:
      default:
        - NDArray
    output_schemas:
      default:
        - NDArray
client:
  port: 65322
  output_names:
    - output
  input_data_format: JSON
  output_data_format: NUMPY
