serving:
  http_port: 65322
  log_timings: True
  create_logging_endpoints: True
  extra_start_args:
    -Xmx8g
  output_data_format: NUMPY
steps:
  dl4j_inference_step:
    type: DL4J
    model_loading_path: C:\\Users\\chiaw\\Documents\\data\\konduit-serving-use-cases\\3-2-DL4J-LSTMTextClassification-SingleStep\\bert.zip #C:\\Users\\chiaw\\AppData\\Local\\Temp\\dl4j_csv_mln.zip
    input_names:
      - sentence
    input_column_names:
      default:
        - NDArray
    input_schemas:
      default:
        - NDArray
    output_names:
      - token
    output_column_names:
      default:
        - NDArray
    output_schemas:
      default:
        - NDArray
client:
  port: 65322
  output_names:
    - token
  input_data_format: NUMPY
  output_data_format: NUMPY
